export const Consts = {
  //   authTitlesH2: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "20px",
  //       lineHeight: "1.2",
  //       color: "#202225",
  //     },
  //     tablet: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "24px",
  //       lineHeight: "1.1",
  //       color: "#202225",
  //     },
  //   },
  //   authTextSecondary: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "normal",
  //       fontSize: "15px",
  //       lineHeight: "1.4",
  //       color: "#A1ABC9",
  //     },
  //   },
  //   authLink: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "15px",
  //       lineHeight: "1.3",
  //       color: "#7297FF",
  //     },
  //   },
  //   authButton: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "15px",
  //       lineHeight: "1.3",
  //       color: "#FFFFFF",
  //       background: "#7297FF",
  //       borderRadius: "8px",
  //     },
  //     tablet: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "17px",
  //       lineHeight: "1.41",
  //       color: "#FFFFFF",
  //       background: "#7297FF",
  //       borderRadius: "8px",
  //     },
  //   },
  //   appointmentTap: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "15px",
  //       lineHeight: "1.3",
  //       color: "#FFFFFF",
  //       background: "#7297FF",
  //       borderRadius: "8px",
  //     },
  //   },
  //   appointmentsTextSecondary: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "normal",
  //       fontSize: "13px",
  //       lineHeight: "1.3",
  //       color: "#A1ABC9",
  //     },
  //   },
  //   appointmentButton: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "15px",
  //       lineHeight: "1.3",
  //       color: "#FFFFFF",
  //       background: "#7297FF",
  //       borderRadius: "8px",
  //     },
  //   },
  //   appointmentText: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "normal",
  //       fontSize: "15px",
  //       lineHeight: "1.4",
  //       color: "#202225",
  //     },
  //   },
  //   appointmentCardName: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "17px",
  //       lineHeight: "1.3",
  //       color: "#202225",
  //     },
  //   },
  //   appointmentCardDate: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "15px",
  //       lineHeight: "1.3",
  //       color: "#202225",
  //     },
  //   },
  //   appointmentUserName: {
  //     tablet: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "600",
  //       fontSize: "15px",
  //       lineHeight: "1.3",
  //       color: "#202225",
  //     },
  //   },
  //   appointmentUserRole: {
  //     tablet: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "500",
  //       fontSize: "13px",
  //       lineHeight: "1.3",
  //       color: "#A1ABC9",
  //     },
  //   },
  //   makeAppointmentTitleH4: {
  //     mobile: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "500",
  //       fontSize: "17px",
  //       lineHeight: "1.41",
  //       color: "#A1ABC9",
  //     },
  //   },
  //   makeAppointmentLabel: {
  //     tablet: {
  //       fontFamily: "Poppins",
  //       fontStyle: "normal",
  //       fontWeight: "500",
  //       fontSize: "13px",
  //       lineHeight: "1.3",
  //       color: "#000000",
  //     },
  //   },
};
