export const theme = {
  colors: {
    baseColor: "#202225",
    errorTextColor: "#f6657f",
    accentColor: "#7297ff",
    buttonHoverColor: "#476CD3",
    disabledButtonColor: "#DCE0EC",
    alterButtonBackgroundColor: "#DCE0EC",
    secondaryTextColor: "#a1abc9",
    asideBackgroundColor: "#f9faff",
    inputBackgroundColor: "#ffffff",
    buttonTextColor: "#ffffff",
    inputBorderColor: "#dce0ec",
    viewPagesBackgroundColor: "#f9faff",
    viewPagesContainerBackgroundColor: "#e4ebff",
    pointerColor: "#34c197",
    disabledBackground: "#DCE0EC",
    userStatusColor: "#34C197",
  },
  inputsBorders: {
    asideInputBorder: "1px solid #dce0ec",
    asideInputErrorBorder: "1px solid #ff2567",
    asideInputFocusBorder: "1px solid #7297ff",
  },
  borderRadius: {
    inputsBorderRadius: "8px",
    buttonsBorderRadius: "8px",
    borderRadius: "8px",
  },
  fonts: {
    fontFamily: "Poppins",
    fontStyleNormal: "normal",
    fontWeightNormal: "normal",
    fontWeightBold: "600",
    fontWeightMedium: "500",
    mobileFontSize: "15px",
    fontSize20: "20px",
    fontSize24: "24px",
    fontSize15: "15px",
    fontSize17: "17px",
    fontSize13: "13px",
    lineHeight120: "1.2",
    lineHeight130: "1.3",
    lineHeight141: "1.41",
    lineHeight110: "1.1",
    lineHeight160: "1.6",

  },
  media: {
    mobile: "screen and (min-width: 320px)",
    tablet: "screen and (min-width: 768px)",
    desktop: "screen and (min-width: 1920px)",
  },
};
